name: Notify ramp-widget

on:
  push:
    branches:
      - playwright

jobs:
  notify-ramp-widget:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: vasanthbaiondata/ramp-widget
          event-type: submodule-updated
          client-payload: '{"ref": "playwright-integration"}'
