name: Notify ramp-widget

on:
  push:
    branches:
      - playwright  # When you push to 'playwright' branch in QA repo

jobs:
  notify-ramp-widget:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to ramp-widget
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}   # PAT with repo access
          repository: Transfi/transfi-ramp-widget       # Target repo
          event-type: submodule-updated                 # Event name
          client-payload: '{"ref": "playwright-integration"}'  # Branch to run in ramp-widget
