name: Trigger QA Automation Widget

on:
  workflow_dispatch: # manually trigger this workflow

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Transfi QA Automation Widget
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.Personal Access Token }}   # your PAT
          repository: Transfi/transfi-qa-automation-widget
          event-type: trigger-from-ramp
          client-payload: |
            {
              "source": "ramp-workflow",
              "triggered_by": "main-workflow"
            }
