name: Playwright E2E Tests & Deploy Project + Report

on:
  push:
    branches:
      - playwright
  workflow_dispatch:
  schedule:
    # Run every day at 9:30 AM IST (which is 4:00 AM UTC)
    - cron: '30 4 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Playwright E2E tests
      - name: Run Playwright tests
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            # Daily scheduled run → only run login group, no reports
            TEST_GROUP=login npx playwright install
            TEST_GROUP=login npx playwright test --reporter=line
          else
            # Normal branch push or manual run → full tests with HTML report
            TEST_GROUP=E2E npx playwright install
            TEST_GROUP=E2E npx playwright test --reporter=html
          fi

      # 5. Deploy full project to Vercel (only on push/dispatch, not schedule)
      - name: Deploy full project to Vercel
        if: github.event_name != 'schedule'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: true

      # 6. Deploy Playwright HTML report (only on push/dispatch, not schedule)
      - name: Deploy Playwright HTML report to Vercel
        if: github.event_name != 'schedule'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: playwright-report
          prod: false
