name: Notify Transfi App

on:
  push:
    branches:
      - main

jobs:
  notify-transfi-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          # PAT with repo + workflow scope
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: vasanthbaiondata/Transfi_App
          event-type: submodule-updated
