name: Notify Repo 2

on:
  push:
    branches:
      - playwright   # or any branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to Repo 2
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}   # PAT with repo access
          repository: Transfi/transfi-qa-automation-widget
          event-type: trigger-from-ramp
